from setuptools import setup

setup(
    name='MLEx3',
    version='',
    packages=['BoVW', 'util', 'util.classifiers', 'venv.Lib.site-packages.bin', 'venv.Lib.site-packages.cv2',
              'venv.Lib.site-packages.cv2.data', 'venv.Lib.site-packages.PIL', 'venv.Lib.site-packages.absl',
              'venv.Lib.site-packages.absl.flags', 'venv.Lib.site-packages.absl.logging',
              'venv.Lib.site-packages.absl.testing', 'venv.Lib.site-packages.absl.third_party',
              'venv.Lib.site-packages.absl.third_party.unittest3_backport', 'venv.Lib.site-packages.docs',
              'venv.Lib.site-packages.gast', 'venv.Lib.site-packages.grpc', 'venv.Lib.site-packages.grpc.beta',
              'venv.Lib.site-packages.grpc._cython', 'venv.Lib.site-packages.grpc._cython._cygrpc',
              'venv.Lib.site-packages.grpc.framework', 'venv.Lib.site-packages.grpc.framework.common',
              'venv.Lib.site-packages.grpc.framework.foundation', 'venv.Lib.site-packages.grpc.framework.interfaces',
              'venv.Lib.site-packages.grpc.framework.interfaces.base',
              'venv.Lib.site-packages.grpc.framework.interfaces.face', 'venv.Lib.site-packages.grpc.experimental',
              'venv.Lib.site-packages.h5py', 'venv.Lib.site-packages.h5py._hl', 'venv.Lib.site-packages.h5py.tests',
              'venv.Lib.site-packages.h5py.tests.hl', 'venv.Lib.site-packages.h5py.tests.hl.test_vds',
              'venv.Lib.site-packages.h5py.tests.old', 'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.yaml',
              'venv.Lib.site-packages.astor', 'venv.Lib.site-packages.keras', 'venv.Lib.site-packages.keras.utils',
              'venv.Lib.site-packages.keras.engine', 'venv.Lib.site-packages.keras.layers',
              'venv.Lib.site-packages.keras.legacy', 'venv.Lib.site-packages.keras.backend',
              'venv.Lib.site-packages.keras.datasets', 'venv.Lib.site-packages.keras.wrappers',
              'venv.Lib.site-packages.keras.applications', 'venv.Lib.site-packages.keras.preprocessing',
              'venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing._private',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.scipy', 'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.signal.windows', 'venv.Lib.site-packages.scipy.sparse',
              'venv.Lib.site-packages.scipy.sparse.tests', 'venv.Lib.site-packages.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.spatial.transform',
              'venv.Lib.site-packages.scipy.spatial.transform.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.optimize._shgo_lib',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.cli',
              'venv.Lib.site-packages.google.protobuf', 'venv.Lib.site-packages.google.protobuf.util',
              'venv.Lib.site-packages.google.protobuf.pyext', 'venv.Lib.site-packages.google.protobuf.compiler',
              'venv.Lib.site-packages.google.protobuf.internal',
              'venv.Lib.site-packages.google.protobuf.internal.import_test_package', 'venv.Lib.site-packages.pandas',
              'venv.Lib.site-packages.pandas.io', 'venv.Lib.site-packages.pandas.io.sas',
              'venv.Lib.site-packages.pandas.io.json', 'venv.Lib.site-packages.pandas.io.formats',
              'venv.Lib.site-packages.pandas.io.msgpack', 'venv.Lib.site-packages.pandas.io.clipboard',
              'venv.Lib.site-packages.pandas.api', 'venv.Lib.site-packages.pandas.api.types',
              'venv.Lib.site-packages.pandas.api.extensions', 'venv.Lib.site-packages.pandas.core',
              'venv.Lib.site-packages.pandas.core.util', 'venv.Lib.site-packages.pandas.core.tools',
              'venv.Lib.site-packages.pandas.core.arrays', 'venv.Lib.site-packages.pandas.core.dtypes',
              'venv.Lib.site-packages.pandas.core.sparse', 'venv.Lib.site-packages.pandas.core.groupby',
              'venv.Lib.site-packages.pandas.core.indexes', 'venv.Lib.site-packages.pandas.core.reshape',
              'venv.Lib.site-packages.pandas.core.internals', 'venv.Lib.site-packages.pandas.core.computation',
              'venv.Lib.site-packages.pandas.util', 'venv.Lib.site-packages.pandas._libs',
              'venv.Lib.site-packages.pandas._libs.tslibs', 'venv.Lib.site-packages.pandas.tests',
              'venv.Lib.site-packages.pandas.tests.io', 'venv.Lib.site-packages.pandas.tests.io.sas',
              'venv.Lib.site-packages.pandas.tests.io.json', 'venv.Lib.site-packages.pandas.tests.io.parser',
              'venv.Lib.site-packages.pandas.tests.io.formats', 'venv.Lib.site-packages.pandas.tests.io.msgpack',
              'venv.Lib.site-packages.pandas.tests.api', 'venv.Lib.site-packages.pandas.tests.util',
              'venv.Lib.site-packages.pandas.tests.frame', 'venv.Lib.site-packages.pandas.tests.tools',
              'venv.Lib.site-packages.pandas.tests.arrays', 'venv.Lib.site-packages.pandas.tests.arrays.sparse',
              'venv.Lib.site-packages.pandas.tests.arrays.interval',
              'venv.Lib.site-packages.pandas.tests.arrays.categorical', 'venv.Lib.site-packages.pandas.tests.dtypes',
              'venv.Lib.site-packages.pandas.tests.dtypes.cast', 'venv.Lib.site-packages.pandas.tests.scalar',
              'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.multi',
              'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval',
              'venv.Lib.site-packages.pandas.tests.indexing.multiindex', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.resample', 'venv.Lib.site-packages.pandas.tests.extension',
              'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.arrow',
              'venv.Lib.site-packages.pandas.tests.extension.numpy_',
              'venv.Lib.site-packages.pandas.tests.extension.decimal', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.arithmetic', 'venv.Lib.site-packages.pandas.tests.reductions',
              'venv.Lib.site-packages.pandas.tests.computation', 'venv.Lib.site-packages.pandas.arrays',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.tseries',
              'venv.Lib.site-packages.pandas.plotting', 'venv.Lib.site-packages.theano',
              'venv.Lib.site-packages.theano.gof', 'venv.Lib.site-packages.theano.gof.tests',
              'venv.Lib.site-packages.theano.misc', 'venv.Lib.site-packages.theano.misc.tests',
              'venv.Lib.site-packages.theano.d3viz', 'venv.Lib.site-packages.theano.d3viz.tests',
              'venv.Lib.site-packages.theano.tests', 'venv.Lib.site-packages.theano.compat',
              'venv.Lib.site-packages.theano.scalar', 'venv.Lib.site-packages.theano.scalar.tests',
              'venv.Lib.site-packages.theano.sparse', 'venv.Lib.site-packages.theano.sparse.tests',
              'venv.Lib.site-packages.theano.sparse.sandbox', 'venv.Lib.site-packages.theano.tensor',
              'venv.Lib.site-packages.theano.tensor.nnet', 'venv.Lib.site-packages.theano.tensor.nnet.tests',
              'venv.Lib.site-packages.theano.tensor.tests', 'venv.Lib.site-packages.theano.tensor.signal',
              'venv.Lib.site-packages.theano.tensor.signal.tests', 'venv.Lib.site-packages.theano.compile',
              'venv.Lib.site-packages.theano.compile.tests', 'venv.Lib.site-packages.theano.compile.sandbox',
              'venv.Lib.site-packages.theano.sandbox', 'venv.Lib.site-packages.theano.sandbox.cuda',
              'venv.Lib.site-packages.theano.sandbox.tests', 'venv.Lib.site-packages.theano.sandbox.linalg',
              'venv.Lib.site-packages.theano.sandbox.linalg.tests', 'venv.Lib.site-packages.theano.gpuarray',
              'venv.Lib.site-packages.theano.gpuarray.tests', 'venv.Lib.site-packages.theano.typed_list',
              'venv.Lib.site-packages.theano.typed_list.tests', 'venv.Lib.site-packages.theano.scan_module',
              'venv.Lib.site-packages.theano.scan_module.tests', 'venv.Lib.site-packages.sklearn',
              'venv.Lib.site-packages.sklearn.svm', 'venv.Lib.site-packages.sklearn.svm.tests',
              'venv.Lib.site-packages.sklearn.tree', 'venv.Lib.site-packages.sklearn.tree.tests',
              'venv.Lib.site-packages.sklearn.tests', 'venv.Lib.site-packages.sklearn.utils',
              'venv.Lib.site-packages.sklearn.utils.tests', 'venv.Lib.site-packages.sklearn.utils.sparsetools',
              'venv.Lib.site-packages.sklearn.utils.sparsetools.tests', 'venv.Lib.site-packages.sklearn.cluster',
              'venv.Lib.site-packages.sklearn.cluster.tests', 'venv.Lib.site-packages.sklearn.compose',
              'venv.Lib.site-packages.sklearn.compose.tests', 'venv.Lib.site-packages.sklearn.metrics',
              'venv.Lib.site-packages.sklearn.metrics.tests', 'venv.Lib.site-packages.sklearn.metrics.cluster',
              'venv.Lib.site-packages.sklearn.metrics.cluster.tests', 'venv.Lib.site-packages.sklearn.mixture',
              'venv.Lib.site-packages.sklearn.mixture.tests', 'venv.Lib.site-packages.sklearn.datasets',
              'venv.Lib.site-packages.sklearn.datasets.tests', 'venv.Lib.site-packages.sklearn.ensemble',
              'venv.Lib.site-packages.sklearn.ensemble.tests', 'venv.Lib.site-packages.sklearn.manifold',
              'venv.Lib.site-packages.sklearn.manifold.tests', 'venv.Lib.site-packages.sklearn.externals',
              'venv.Lib.site-packages.sklearn.externals.joblib',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals.loky',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals.loky.backend',
              'venv.Lib.site-packages.sklearn.externals.joblib.externals.cloudpickle',
              'venv.Lib.site-packages.sklearn.neighbors', 'venv.Lib.site-packages.sklearn.neighbors.tests',
              'venv.Lib.site-packages.sklearn.covariance', 'venv.Lib.site-packages.sklearn.covariance.tests',
              'venv.Lib.site-packages.sklearn._build_utils', 'venv.Lib.site-packages.sklearn.linear_model',
              'venv.Lib.site-packages.sklearn.linear_model.tests', 'venv.Lib.site-packages.sklearn.__check_build',
              'venv.Lib.site-packages.sklearn.decomposition', 'venv.Lib.site-packages.sklearn.decomposition.tests',
              'venv.Lib.site-packages.sklearn.preprocessing', 'venv.Lib.site-packages.sklearn.preprocessing.tests',
              'venv.Lib.site-packages.sklearn.neural_network', 'venv.Lib.site-packages.sklearn.neural_network.tests',
              'venv.Lib.site-packages.sklearn.model_selection', 'venv.Lib.site-packages.sklearn.model_selection.tests',
              'venv.Lib.site-packages.sklearn.semi_supervised', 'venv.Lib.site-packages.sklearn.semi_supervised.tests',
              'venv.Lib.site-packages.sklearn.gaussian_process',
              'venv.Lib.site-packages.sklearn.gaussian_process.tests',
              'venv.Lib.site-packages.sklearn.feature_selection',
              'venv.Lib.site-packages.sklearn.feature_selection.tests',
              'venv.Lib.site-packages.sklearn.feature_extraction',
              'venv.Lib.site-packages.sklearn.feature_extraction.tests',
              'venv.Lib.site-packages.sklearn.cross_decomposition',
              'venv.Lib.site-packages.sklearn.cross_decomposition.tests', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.markdown',
              'venv.Lib.site-packages.markdown.extensions', 'venv.Lib.site-packages.werkzeug',
              'venv.Lib.site-packages.werkzeug.debug', 'venv.Lib.site-packages.werkzeug.contrib',
              'venv.Lib.site-packages.matplotlib', 'venv.Lib.site-packages.matplotlib.tri',
              'venv.Lib.site-packages.matplotlib.axes', 'venv.Lib.site-packages.matplotlib.cbook',
              'venv.Lib.site-packages.matplotlib.style', 'venv.Lib.site-packages.matplotlib.compat',
              'venv.Lib.site-packages.matplotlib.testing', 'venv.Lib.site-packages.matplotlib.testing.jpl_units',
              'venv.Lib.site-packages.matplotlib.backends', 'venv.Lib.site-packages.matplotlib.backends.qt_editor',
              'venv.Lib.site-packages.matplotlib.sphinxext', 'venv.Lib.site-packages.matplotlib.projections',
              'venv.Lib.site-packages.tensorflow', 'venv.Lib.site-packages.tensorflow._api',
              'venv.Lib.site-packages.tensorflow._api.v1', 'venv.Lib.site-packages.tensorflow._api.v1.io',
              'venv.Lib.site-packages.tensorflow._api.v1.nn', 'venv.Lib.site-packages.tensorflow._api.v1.nn.rnn_cell',
              'venv.Lib.site-packages.tensorflow._api.v1.app', 'venv.Lib.site-packages.tensorflow._api.v1.data',
              'venv.Lib.site-packages.tensorflow._api.v1.data.experimental',
              'venv.Lib.site-packages.tensorflow._api.v1.math', 'venv.Lib.site-packages.tensorflow._api.v1.sets',
              'venv.Lib.site-packages.tensorflow._api.v1.test', 'venv.Lib.site-packages.tensorflow._api.v1.gfile',
              'venv.Lib.site-packages.tensorflow._api.v1.image', 'venv.Lib.site-packages.tensorflow._api.v1.keras',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.utils',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.layers',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.losses',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.models',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.backend',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.metrics',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.imdb',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.mnist',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.cifar10',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.reuters',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.cifar100',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.fashion_mnist',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.datasets.boston_housing',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.wrappers',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.wrappers.scikit_learn',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.callbacks',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.estimator',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.optimizers',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.activations',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.constraints',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.vgg16',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.vgg19',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.nasnet',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.densenet',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.resnet50',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.xception',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.mobilenet',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.inception_v3',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.mobilenet_v2',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.applications.inception_resnet_v2',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.initializers',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.regularizers',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.preprocessing',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.preprocessing.text',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.preprocessing.image',
              'venv.Lib.site-packages.tensorflow._api.v1.keras.preprocessing.sequence',
              'venv.Lib.site-packages.tensorflow._api.v1.manip', 'venv.Lib.site-packages.tensorflow._api.v1.train',
              'venv.Lib.site-packages.tensorflow._api.v1.train.queue_runner',
              'venv.Lib.site-packages.tensorflow._api.v1.compat', 'venv.Lib.site-packages.tensorflow._api.v1.dtypes',
              'venv.Lib.site-packages.tensorflow._api.v1.errors', 'venv.Lib.site-packages.tensorflow._api.v1.layers',
              'venv.Lib.site-packages.tensorflow._api.v1.linalg', 'venv.Lib.site-packages.tensorflow._api.v1.losses',
              'venv.Lib.site-packages.tensorflow._api.v1.random', 'venv.Lib.site-packages.tensorflow._api.v1.sparse',
              'venv.Lib.site-packages.tensorflow._api.v1.bitwise', 'venv.Lib.site-packages.tensorflow._api.v1.logging',
              'venv.Lib.site-packages.tensorflow._api.v1.metrics', 'venv.Lib.site-packages.tensorflow._api.v1.strings',
              'venv.Lib.site-packages.tensorflow._api.v1.summary', 'venv.Lib.site-packages.tensorflow._api.v1.profiler',
              'venv.Lib.site-packages.tensorflow._api.v1.spectral',
              'venv.Lib.site-packages.tensorflow._api.v1.user_ops',
              'venv.Lib.site-packages.tensorflow._api.v1.debugging',
              'venv.Lib.site-packages.tensorflow._api.v1.python_io',
              'venv.Lib.site-packages.tensorflow._api.v1.sysconfig',
              'venv.Lib.site-packages.tensorflow._api.v1.graph_util',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.utils',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.loader',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.builder',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.main_op',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.constants',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.tag_constants',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.signature_constants',
              'venv.Lib.site-packages.tensorflow._api.v1.saved_model.signature_def_utils',
              'venv.Lib.site-packages.tensorflow._api.v1.initializers',
              'venv.Lib.site-packages.tensorflow._api.v1.quantization',
              'venv.Lib.site-packages.tensorflow._api.v1.distributions',
              'venv.Lib.site-packages.tensorflow._api.v1.feature_column',
              'venv.Lib.site-packages.tensorflow._api.v1.resource_loader', 'venv.Lib.site-packages.tensorflow.core',
              'venv.Lib.site-packages.tensorflow.core.lib', 'venv.Lib.site-packages.tensorflow.core.lib.core',
              'venv.Lib.site-packages.tensorflow.core.util', 'venv.Lib.site-packages.tensorflow.core.debug',
              'venv.Lib.site-packages.tensorflow.core.example', 'venv.Lib.site-packages.tensorflow.core.kernels',
              'venv.Lib.site-packages.tensorflow.core.kernels.boosted_trees',
              'venv.Lib.site-packages.tensorflow.core.grappler',
              'venv.Lib.site-packages.tensorflow.core.grappler.costs',
              'venv.Lib.site-packages.tensorflow.core.profiler', 'venv.Lib.site-packages.tensorflow.core.protobuf',
              'venv.Lib.site-packages.tensorflow.core.framework', 'venv.Lib.site-packages.tensorflow.tools',
              'venv.Lib.site-packages.tensorflow.tools.docs', 'venv.Lib.site-packages.tensorflow.tools.dist_test',
              'venv.Lib.site-packages.tensorflow.tools.dist_test.server',
              'venv.Lib.site-packages.tensorflow.tools.pip_package',
              'venv.Lib.site-packages.tensorflow.tools.graph_transforms', 'venv.Lib.site-packages.tensorflow.python',
              'venv.Lib.site-packages.tensorflow.python.lib', 'venv.Lib.site-packages.tensorflow.python.lib.io',
              'venv.Lib.site-packages.tensorflow.python.ops', 'venv.Lib.site-packages.tensorflow.python.ops.linalg',
              'venv.Lib.site-packages.tensorflow.python.ops.losses',
              'venv.Lib.site-packages.tensorflow.python.ops.parallel_for',
              'venv.Lib.site-packages.tensorflow.python.ops.distributions',
              'venv.Lib.site-packages.tensorflow.python.data', 'venv.Lib.site-packages.tensorflow.python.data.ops',
              'venv.Lib.site-packages.tensorflow.python.data.util',
              'venv.Lib.site-packages.tensorflow.python.data.experimental',
              'venv.Lib.site-packages.tensorflow.python.data.experimental.ops',
              'venv.Lib.site-packages.tensorflow.python.data.experimental.kernel_tests',
              'venv.Lib.site-packages.tensorflow.python.data.experimental.kernel_tests.serialization',
              'venv.Lib.site-packages.tensorflow.python.data.kernel_tests',
              'venv.Lib.site-packages.tensorflow.python.util', 'venv.Lib.site-packages.tensorflow.python.util.protobuf',
              'venv.Lib.site-packages.tensorflow.python.debug', 'venv.Lib.site-packages.tensorflow.python.debug.cli',
              'venv.Lib.site-packages.tensorflow.python.debug.lib',
              'venv.Lib.site-packages.tensorflow.python.debug.wrappers',
              'venv.Lib.site-packages.tensorflow.python.eager', 'venv.Lib.site-packages.tensorflow.python.keras',
              'venv.Lib.site-packages.tensorflow.python.keras.utils',
              'venv.Lib.site-packages.tensorflow.python.keras.engine',
              'venv.Lib.site-packages.tensorflow.python.keras.layers',
              'venv.Lib.site-packages.tensorflow.python.keras.datasets',
              'venv.Lib.site-packages.tensorflow.python.keras.wrappers',
              'venv.Lib.site-packages.tensorflow.python.keras.estimator',
              'venv.Lib.site-packages.tensorflow.python.keras.applications',
              'venv.Lib.site-packages.tensorflow.python.keras.preprocessing',
              'venv.Lib.site-packages.tensorflow.python.tools', 'venv.Lib.site-packages.tensorflow.python.tools.api',
              'venv.Lib.site-packages.tensorflow.python.tools.api.generator',
              'venv.Lib.site-packages.tensorflow.python.client', 'venv.Lib.site-packages.tensorflow.python.compat',
              'venv.Lib.site-packages.tensorflow.python.layers', 'venv.Lib.site-packages.tensorflow.python.summary',
              'venv.Lib.site-packages.tensorflow.python.summary.writer',
              'venv.Lib.site-packages.tensorflow.python.grappler', 'venv.Lib.site-packages.tensorflow.python.platform',
              'venv.Lib.site-packages.tensorflow.python.profiler',
              'venv.Lib.site-packages.tensorflow.python.profiler.internal',
              'venv.Lib.site-packages.tensorflow.python.training',
              'venv.Lib.site-packages.tensorflow.python.training.checkpointable',
              'venv.Lib.site-packages.tensorflow.python.user_ops', 'venv.Lib.site-packages.tensorflow.python.autograph',
              'venv.Lib.site-packages.tensorflow.python.autograph.core',
              'venv.Lib.site-packages.tensorflow.python.autograph.impl',
              'venv.Lib.site-packages.tensorflow.python.autograph.lang',
              'venv.Lib.site-packages.tensorflow.python.autograph.pyct',
              'venv.Lib.site-packages.tensorflow.python.autograph.pyct.static_analysis',
              'venv.Lib.site-packages.tensorflow.python.autograph.pyct.common_transformers',
              'venv.Lib.site-packages.tensorflow.python.autograph.utils',
              'venv.Lib.site-packages.tensorflow.python.autograph.operators',
              'venv.Lib.site-packages.tensorflow.python.autograph.converters',
              'venv.Lib.site-packages.tensorflow.python.estimator',
              'venv.Lib.site-packages.tensorflow.python.estimator.api',
              'venv.Lib.site-packages.tensorflow.python.estimator.api.estimator',
              'venv.Lib.site-packages.tensorflow.python.estimator.api.estimator.export',
              'venv.Lib.site-packages.tensorflow.python.estimator.api.estimator.inputs',
              'venv.Lib.site-packages.tensorflow.python.estimator.canned',
              'venv.Lib.site-packages.tensorflow.python.estimator.export',
              'venv.Lib.site-packages.tensorflow.python.estimator.inputs',
              'venv.Lib.site-packages.tensorflow.python.estimator.inputs.queues',
              'venv.Lib.site-packages.tensorflow.python.framework',
              'venv.Lib.site-packages.tensorflow.python.distribute',
              'venv.Lib.site-packages.tensorflow.python.saved_model',
              'venv.Lib.site-packages.tensorflow.python.feature_column', 'venv.Lib.site-packages.tensorflow.contrib',
              'venv.Lib.site-packages.tensorflow.contrib.nn', 'venv.Lib.site-packages.tensorflow.contrib.nn.python',
              'venv.Lib.site-packages.tensorflow.contrib.nn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.crf', 'venv.Lib.site-packages.tensorflow.contrib.crf.python',
              'venv.Lib.site-packages.tensorflow.contrib.crf.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.gan', 'venv.Lib.site-packages.tensorflow.contrib.gan.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.eval',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.eval.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.losses',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.losses.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.features',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.features.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.estimator',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.estimator.python',
              'venv.Lib.site-packages.tensorflow.contrib.opt', 'venv.Lib.site-packages.tensorflow.contrib.opt.python',
              'venv.Lib.site-packages.tensorflow.contrib.opt.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.rnn', 'venv.Lib.site-packages.tensorflow.contrib.rnn.ops',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python.tools',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.rpc', 'venv.Lib.site-packages.tensorflow.contrib.rpc.python',
              'venv.Lib.site-packages.tensorflow.contrib.rpc.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.rpc.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.tpu', 'venv.Lib.site-packages.tensorflow.contrib.tpu.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.proto',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python.tpu',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python.profiler',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.profiler',
              'venv.Lib.site-packages.tensorflow.contrib.data', 'venv.Lib.site-packages.tensorflow.contrib.data.python',
              'venv.Lib.site-packages.tensorflow.contrib.data.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.lite', 'venv.Lib.site-packages.tensorflow.contrib.lite.toco',
              'venv.Lib.site-packages.tensorflow.contrib.lite.toco.python',
              'venv.Lib.site-packages.tensorflow.contrib.lite.python',
              'venv.Lib.site-packages.tensorflow.contrib.lite.python.interpreter_wrapper',
              'venv.Lib.site-packages.tensorflow.contrib.nccl', 'venv.Lib.site-packages.tensorflow.contrib.nccl.ops',
              'venv.Lib.site-packages.tensorflow.contrib.nccl.python',
              'venv.Lib.site-packages.tensorflow.contrib.nccl.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.rate', 'venv.Lib.site-packages.tensorflow.contrib.slim',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python.slim',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python.slim.data',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python.slim.nets',
              'venv.Lib.site-packages.tensorflow.contrib.text', 'venv.Lib.site-packages.tensorflow.contrib.text.python',
              'venv.Lib.site-packages.tensorflow.contrib.text.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.util', 'venv.Lib.site-packages.tensorflow.contrib.cmake',
              'venv.Lib.site-packages.tensorflow.contrib.cmake.tools',
              'venv.Lib.site-packages.tensorflow.contrib.coder',
              'venv.Lib.site-packages.tensorflow.contrib.coder.python',
              'venv.Lib.site-packages.tensorflow.contrib.coder.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.eager',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.gan',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.l2hmc',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.spinn',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.revnet',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.rnn_ptb',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.densenet',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.resnet50',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.rnn_colorbot',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python.examples.linear_regression',
              'venv.Lib.site-packages.tensorflow.contrib.hooks',
              'venv.Lib.site-packages.tensorflow.contrib.hooks.python',
              'venv.Lib.site-packages.tensorflow.contrib.hooks.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.image', 'venv.Lib.site-packages.tensorflow.contrib.image.ops',
              'venv.Lib.site-packages.tensorflow.contrib.image.python',
              'venv.Lib.site-packages.tensorflow.contrib.image.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.keras', 'venv.Lib.site-packages.tensorflow.contrib.keras.api',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.utils',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.layers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.losses',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.models',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.backend',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.metrics',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.imdb',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.mnist',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar10',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.reuters',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar100',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.boston_housing',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.wrappers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.wrappers.scikit_learn',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.callbacks',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.optimizers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.activations',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.constraints',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg16',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg19',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.resnet50',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.xception',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.mobilenet',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.inception_v3',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.initializers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.regularizers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.text',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.image',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.sequence',
              'venv.Lib.site-packages.tensorflow.contrib.learn',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.ops',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.utils',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.datasets',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.learn_io',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.estimators',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.preprocessing',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.preprocessing.tests',
              'venv.Lib.site-packages.tensorflow.contrib.proto',
              'venv.Lib.site-packages.tensorflow.contrib.proto.python',
              'venv.Lib.site-packages.tensorflow.contrib.proto.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.specs',
              'venv.Lib.site-packages.tensorflow.contrib.specs.python',
              'venv.Lib.site-packages.tensorflow.contrib.hadoop',
              'venv.Lib.site-packages.tensorflow.contrib.hadoop.python',
              'venv.Lib.site-packages.tensorflow.contrib.hadoop.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.ignite',
              'venv.Lib.site-packages.tensorflow.contrib.ignite.python',
              'venv.Lib.site-packages.tensorflow.contrib.ignite.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.layers',
              'venv.Lib.site-packages.tensorflow.contrib.layers.ops',
              'venv.Lib.site-packages.tensorflow.contrib.layers.python',
              'venv.Lib.site-packages.tensorflow.contrib.layers.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.layers.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm.ops',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm.python',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.lookup', 'venv.Lib.site-packages.tensorflow.contrib.losses',
              'venv.Lib.site-packages.tensorflow.contrib.losses.python',
              'venv.Lib.site-packages.tensorflow.contrib.losses.python.losses',
              'venv.Lib.site-packages.tensorflow.contrib.losses.python.metric_learning',
              'venv.Lib.site-packages.tensorflow.contrib.signal',
              'venv.Lib.site-packages.tensorflow.contrib.signal.python',
              'venv.Lib.site-packages.tensorflow.contrib.signal.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.signal.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.tfprof', 'venv.Lib.site-packages.tensorflow.contrib.metrics',
              'venv.Lib.site-packages.tensorflow.contrib.metrics.python',
              'venv.Lib.site-packages.tensorflow.contrib.metrics.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.metrics.python.metrics',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.ops',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.python',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.solvers',
              'venv.Lib.site-packages.tensorflow.contrib.solvers.python',
              'venv.Lib.site-packages.tensorflow.contrib.solvers.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.staging', 'venv.Lib.site-packages.tensorflow.contrib.summary',
              'venv.Lib.site-packages.tensorflow.contrib.testing',
              'venv.Lib.site-packages.tensorflow.contrib.testing.python',
              'venv.Lib.site-packages.tensorflow.contrib.testing.python.framework',
              'venv.Lib.site-packages.tensorflow.contrib.batching',
              'venv.Lib.site-packages.tensorflow.contrib.batching.python',
              'venv.Lib.site-packages.tensorflow.contrib.batching.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.compiler',
              'venv.Lib.site-packages.tensorflow.contrib.grid_rnn',
              'venv.Lib.site-packages.tensorflow.contrib.grid_rnn.python',
              'venv.Lib.site-packages.tensorflow.contrib.grid_rnn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.quantize',
              'venv.Lib.site-packages.tensorflow.contrib.quantize.python',
              'venv.Lib.site-packages.tensorflow.contrib.training',
              'venv.Lib.site-packages.tensorflow.contrib.training.python',
              'venv.Lib.site-packages.tensorflow.contrib.training.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.autograph',
              'venv.Lib.site-packages.tensorflow.contrib.bayesflow',
              'venv.Lib.site-packages.tensorflow.contrib.bayesflow.python',
              'venv.Lib.site-packages.tensorflow.contrib.bayesflow.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn.python',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.estimator',
              'venv.Lib.site-packages.tensorflow.contrib.estimator.python',
              'venv.Lib.site-packages.tensorflow.contrib.estimator.python.estimator',
              'venv.Lib.site-packages.tensorflow.contrib.framework',
              'venv.Lib.site-packages.tensorflow.contrib.framework.python',
              'venv.Lib.site-packages.tensorflow.contrib.framework.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.framework.python.framework',
              'venv.Lib.site-packages.tensorflow.contrib.integrate',
              'venv.Lib.site-packages.tensorflow.contrib.integrate.python',
              'venv.Lib.site-packages.tensorflow.contrib.integrate.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.predictor',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent.python',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.resampler',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.ops',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.python',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.sparsemax',
              'venv.Lib.site-packages.tensorflow.contrib.sparsemax.python',
              'venv.Lib.site-packages.tensorflow.contrib.sparsemax.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.stateless',
              'venv.Lib.site-packages.tensorflow.contrib.all_reduce',
              'venv.Lib.site-packages.tensorflow.contrib.all_reduce.python',
              'venv.Lib.site-packages.tensorflow.contrib.checkpoint',
              'venv.Lib.site-packages.tensorflow.contrib.checkpoint.python',
              'venv.Lib.site-packages.tensorflow.contrib.copy_graph',
              'venv.Lib.site-packages.tensorflow.contrib.copy_graph.python',
              'venv.Lib.site-packages.tensorflow.contrib.copy_graph.python.util',
              'venv.Lib.site-packages.tensorflow.contrib.deprecated',
              'venv.Lib.site-packages.tensorflow.contrib.distribute',
              'venv.Lib.site-packages.tensorflow.contrib.distribute.python',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.python',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.python.timeseries',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.python.timeseries.state_space_models',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.examples',
              'venv.Lib.site-packages.tensorflow.contrib.saved_model',
              'venv.Lib.site-packages.tensorflow.contrib.saved_model.python',
              'venv.Lib.site-packages.tensorflow.contrib.saved_model.python.saved_model',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard.plugins',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard.plugins.projector',
              'venv.Lib.site-packages.tensorflow.contrib.graph_editor',
              'venv.Lib.site-packages.tensorflow.contrib.graph_editor.tests',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.ops',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.python',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.optimizer_v2',
              'venv.Lib.site-packages.tensorflow.contrib.quantization',
              'venv.Lib.site-packages.tensorflow.contrib.quantization.python',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.lib',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.lib.learner',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.lib.learner.batch',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.proto',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.utils',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.training.functions',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.estimator_batch',
              'venv.Lib.site-packages.tensorflow.contrib.distributions',
              'venv.Lib.site-packages.tensorflow.contrib.distributions.python',
              'venv.Lib.site-packages.tensorflow.contrib.distributions.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.distributions.python.ops.bijectors',
              'venv.Lib.site-packages.tensorflow.contrib.factorization',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.python',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning.python',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.proto',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.client',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.models',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.python',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.decision_trees',
              'venv.Lib.site-packages.tensorflow.contrib.decision_trees.proto',
              'venv.Lib.site-packages.tensorflow.contrib.feature_column',
              'venv.Lib.site-packages.tensorflow.contrib.feature_column.python',
              'venv.Lib.site-packages.tensorflow.contrib.feature_column.python.feature_column',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.ops',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.python',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.kernel_methods',
              'venv.Lib.site-packages.tensorflow.contrib.kernel_methods.python',
              'venv.Lib.site-packages.tensorflow.contrib.kernel_methods.python.mappers',
              'venv.Lib.site-packages.tensorflow.contrib.labeled_tensor',
              'venv.Lib.site-packages.tensorflow.contrib.labeled_tensor.python',
              'venv.Lib.site-packages.tensorflow.contrib.labeled_tensor.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.legacy_seq2seq',
              'venv.Lib.site-packages.tensorflow.contrib.legacy_seq2seq.python',
              'venv.Lib.site-packages.tensorflow.contrib.legacy_seq2seq.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.session_bundle',
              'venv.Lib.site-packages.tensorflow.contrib.mixed_precision',
              'venv.Lib.site-packages.tensorflow.contrib.mixed_precision.python',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field.python',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field.python.util',
              'venv.Lib.site-packages.tensorflow.contrib.stat_summarizer',
              'venv.Lib.site-packages.tensorflow.contrib.cluster_resolver',
              'venv.Lib.site-packages.tensorflow.contrib.cluster_resolver.python',
              'venv.Lib.site-packages.tensorflow.contrib.cluster_resolver.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer.python',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor.python',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.ops',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.python',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.periodic_resample',
              'venv.Lib.site-packages.tensorflow.contrib.periodic_resample.python',
              'venv.Lib.site-packages.tensorflow.contrib.periodic_resample.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph.pylib',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.meta_graph_transform',
              'venv.Lib.site-packages.tensorflow.contrib.constrained_optimization',
              'venv.Lib.site-packages.tensorflow.contrib.constrained_optimization.python',
              'venv.Lib.site-packages.tensorflow.compiler', 'venv.Lib.site-packages.tensorflow.compiler.jit',
              'venv.Lib.site-packages.tensorflow.compiler.jit.ops', 'venv.Lib.site-packages.tensorflow.compiler.xla',
              'venv.Lib.site-packages.tensorflow.compiler.xla.service',
              'venv.Lib.site-packages.tensorflow.compiler.xla.python_api',
              'venv.Lib.site-packages.tensorflow.compiler.xla.experimental',
              'venv.Lib.site-packages.tensorflow.compiler.xla.experimental.xla_sharding',
              'venv.Lib.site-packages.tensorflow.examples', 'venv.Lib.site-packages.tensorflow.examples.tutorials',
              'venv.Lib.site-packages.tensorflow.examples.tutorials.mnist', 'venv.Lib.site-packages.tensorboard',
              'venv.Lib.site-packages.tensorboard._vendor', 'venv.Lib.site-packages.tensorboard._vendor.bleach',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.trie',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.filters',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.serializer',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.tensorboard._vendor.tensorflow_serving',
              'venv.Lib.site-packages.tensorboard._vendor.tensorflow_serving.apis',
              'venv.Lib.site-packages.tensorboard._vendor.tensorflow_serving.util',
              'venv.Lib.site-packages.tensorboard._vendor.tensorflow_serving.config',
              'venv.Lib.site-packages.tensorboard._vendor.tensorflow_serving.sources',
              'venv.Lib.site-packages.tensorboard._vendor.tensorflow_serving.sources.storage_path',
              'venv.Lib.site-packages.tensorboard.backend',
              'venv.Lib.site-packages.tensorboard.backend.event_processing',
              'venv.Lib.site-packages.tensorboard.plugins', 'venv.Lib.site-packages.tensorboard.plugins.core',
              'venv.Lib.site-packages.tensorboard.plugins.text', 'venv.Lib.site-packages.tensorboard.plugins.audio',
              'venv.Lib.site-packages.tensorboard.plugins.graph', 'venv.Lib.site-packages.tensorboard.plugins.image',
              'venv.Lib.site-packages.tensorboard.plugins.scalar', 'venv.Lib.site-packages.tensorboard.plugins.profile',
              'venv.Lib.site-packages.tensorboard.plugins.beholder',
              'venv.Lib.site-packages.tensorboard.plugins.debugger',
              'venv.Lib.site-packages.tensorboard.plugins.pr_curve',
              'venv.Lib.site-packages.tensorboard.plugins.histogram',
              'venv.Lib.site-packages.tensorboard.plugins.projector',
              'venv.Lib.site-packages.tensorboard.plugins.distribution',
              'venv.Lib.site-packages.tensorboard.plugins.custom_scalar',
              'venv.Lib.site-packages.tensorboard.plugins.interactive_inference',
              'venv.Lib.site-packages.tensorboard.plugins.interactive_inference.utils',
              'venv.Lib.site-packages.mpl_toolkits.mplot3d', 'venv.Lib.site-packages.mpl_toolkits.axes_grid',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid1', 'venv.Lib.site-packages.mpl_toolkits.axisartist',
              'venv.Lib.site-packages.keras_applications', 'venv.Lib.site-packages.keras_preprocessing',
              'venv.Lib.site-packages.keras_preprocessing.image', 'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='',
    license='',
    author='Diego',
    author_email='',
    description=''
)
